name: terrasoi
description: "Terrasoi App, yaddi yadda"
publish_to: 'none' # This line ensures your package is not accidentally published to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  table_calendar: ^3.0.3
  timezone: ^0.9.3
  flutter_local_notifications: ^17.1.1
  fl_chart: ^0.50.0
  sqflite: ^2.0.0+3
  path_provider: ^2.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/Pictures/
  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/PlayfairDisplay-Italic.ttf
          style: italic
        - asset: assets/fonts/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlayfairDisplay-SemiBold.ttf
          weight: 600
